//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_zaliczenie
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public People()
        {
            this.EmailAddresses = new HashSet<EmailAddresses>();
            this.PhoneNumbers = new HashSet<PhoneNumbers>();
        }
    
        public int ID { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> PhoneBookID { get; set; }
    
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAddresses> EmailAddresses { get; set; }
        public virtual PhoneBooks PhoneBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneNumbers> PhoneNumbers { get; set; }
    }
}
